---
- hosts: kuberesponder-nodes
  become: yes
  vars_files:
  - ../main_centos_variables
  tasks:
  - name: Copying token to all responder
    copy: src={{ token_info }} dest=joining_token

  - name: Joining responders to kubernetes requester
    shell: |
     kubeadm reset -f
     cat joining_token | tail -2 > joiningScripts.sh
     sh joiningScripts.sh