---
# Gathering Facts about the OS

- name: Fetching OS VERSION from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_ver
  changed_when: False

- name: Fetching distro type from /etc/os-release
  when: ansible_os_family is not defined
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro_type
  changed_when: False

- name: Set fact ansible_os_family var to Debian
  when:
    - ansible_os_family is not defined
    - "'Debian' in distro_type.stdout"
  set_fact: 
    ansible_os_family: Debian

- name: Set fact ansible_os_family var to Debian
  when:
    - ansible_os_family is not defined
    - "'Ubuntu' in distro_type.stdout"
  set_fact:
    ansible_os_family: Debian

- name: Set fact ansible_os_family var to RedHat
  when:
    - ansible_os_family is not defined
    - "'CentOS' in distro_type.stdout"
  set_fact:
    ansible_os_family: RedHat

- name: Override config file directory for Debian
  when: ansible_os_family == "Debian"
  set_fact:
    sysconfig_folder: "/etc/default"
