---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --apiserver-advertise-address {{ master_ip }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadminConf }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: "0755"
    remote_src: true

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadminConf }} \
        apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true

- name: copying template YAML file for kubernetes ui access
  template:
    src: "{{ item }}"
    dest: "$HOME/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - "../templates/*.j2"

- name: create user to access kubernetes ui
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadminConf }} \
        apply -f $HOME/oke-admin-user.yml
  register: create_user_result
  until: create_user_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true

- name: allow anonymous access to kubernetes ui
  when: init_cluster is succeeded and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadminConf }} \
        apply -f $HOME/anonymous-access-web.yml
  register: allow_anonymous_result
  until: allow_anonymous_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: true


    
