---
- name: Reloading the firewall
  when: success_config_firewall
  command: |
    firewall-cmd  --reload

- name: Recreate kube-dns
  command: kubectl --kubeconfig={{ kubeadminConf }} -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ groups['requester'][0] }}"
  run_once: true
  ignore_errors: true
